import type { Dispatch, ReactNode, RefObject, SetStateAction } from "react";
import type { Fight, Grid, JudgeApplication, NoteRound, Ring, RingStatus, Room, RoomApplication, RoomBoxer } from "../../../features/auth/authApi";
import type { RequestState } from "../../homeSharedTypes";
import type { RoomSectionVisibility, RoomUiScenarioState } from "../scenario";
import type { FightRow, OwnerTab, PendingApplicationAction, RoomBoxerSortField, RoomTab } from "../types";

export type RoomWorkspaceProps = {
  activeBoxers: RoomBoxer[];
  activeFight: FightRow | null;
  activeJudges: JudgeApplication[];
  activeRing: Ring | null;
  activeRingName: string | null;
  activeRingGrids: Grid[];
  activeRings: Ring[];
  access: {
    canViewPairs: boolean;
    canViewParticipants: boolean;
    canViewRings: boolean;
    canViewRingsOverview: boolean;
    isActiveSideJudge: boolean;
    isChiefJudge: boolean;
    isJudge: boolean;
    isOwner: boolean;
    isSideJudge: boolean;
    isSpectatorGuest: boolean;
    isUnassignedJudge: boolean;
    judgeStatus: JudgeApplication["status"] | null;
  };
  applicationsState: RequestState;
  boxersState: RequestState;
  canSaveOrder: boolean;
  deleteState: RequestState;
  deletingBoxerId: string | null;
  filteredFightRows: FightRow[];
  filteredGrids: Grid[];
  fightRows: FightRow[];
  getJudgeName: (application: JudgeApplication | undefined) => string;
  gridSearch: string;
  gridState: RequestState;
  gridsState: RequestState;
  guestApplicationState: RequestState;
  guestJudgeApplicationState: RequestState;
  guestRoomApplicationStatus: RoomApplication["status"] | null;
  hasPremiumAccess: boolean;
  hasDraftOrder: boolean;
  inactiveBoxers: RoomBoxer[];
  inactiveJudges: JudgeApplication[];
  inactiveRings: Ring[];
  isTimerRunning: boolean;
  isWinnerMenuOpen: boolean;
  judgeApplicationsState: RequestState;
  nextRound: NoteRound | null;
  onGuestApply: () => void;
  onGuestDelete: () => void;
  onGuestEdit: () => void;
  onBoxerDelete: (boxerUuid: string) => void;
  onBoxerEdit: (boxer: RoomBoxer) => void;
  onEditRing: (ringName: string) => void;
  onFightNotesOpen: () => void;
  onFightSelect: Dispatch<SetStateAction<string | null>>;
  onFightStatusChange: Dispatch<SetStateAction<Fight["status"] | null>>;
  onGridOpen: () => void;
  onJudgeChange: (
    applicationUuid: string,
    payload: Partial<Pick<JudgeApplication, "status" | "ring" | "role" | "is_active">>,
  ) => void;
  onJudgeDelete: (applicationUuid: string) => void;
  onJudgeCreate: () => void;
  onJudgeDeleteRequest: () => void;
  onJudgeRingSelect: (applicationUuid: string) => void;
  onOpenRing: (ringName: string) => void;
  onPendingApplicationAction: Dispatch<SetStateAction<PendingApplicationAction | null>>;
  onRoundSelect: Dispatch<SetStateAction<NoteRound | null>>;
  onSaveOrder: () => void;
  onBoxerSearchChange: Dispatch<SetStateAction<string>>;
  onGridSearchChange: Dispatch<SetStateAction<string>>;
  onRingDetailSearchChange: Dispatch<SetStateAction<string>>;
  onTabChange: (tab: RoomTab) => void;
  onTimerDurationChange: (seconds: number) => void;
  onTimerStart: () => void;
  onTimerStop: () => void;
  onToggleBoxer: (boxerUuid: string) => void;
  onToggleRing: (ring: Ring, status: RingStatus) => void;
  onViewModeChange: Dispatch<SetStateAction<"bracket" | "list">>;
  onWinnerConfirm: () => void;
  onWinnerMenuToggle: () => void;
  onWinnerSelect: (boxerUuid: string) => void;
  ownerTab: OwnerTab;
  renderGrid: (grid: Grid, options: { showBuildButton: boolean; readOnly: boolean }) => ReactNode;
  renderGridSortButton: (field: RoomBoxerSortField, label: string) => ReactNode;
  renderRingGrid: (grid: Grid) => ReactNode;
  ringDetailSearch: string;
  ringDetailViewMode: "bracket" | "list";
  ringSideJudgesState: RequestState;
  ringsState: RequestState;
  room: Room;
  roomApplications: RoomApplication[];
  roomJudgeApplications: JudgeApplication[];
  roundTimerSeconds: number;
  roundTimerText: string;
  search: string;
  selectedBoxerIds: string[];
  selectedFightRow: FightRow | null;
  selectedFightWinner: string | null;
  selectedFightWinnerBlueUuid: string;
  selectedFightWinnerRedUuid: string;
  submittedRounds: Set<NoteRound>;
  timerOptions: readonly { label: string; seconds: number }[];
  updateState: RequestState;
  uiScenario: RoomUiScenarioState;
  visibility: RoomSectionVisibility;
  updatingApplicationId: string | null;
  updatingJudgeApplicationId: string | null;
  visiblePairsGrids: Grid[];
  visibleRingTabs: Ring[];
  waitingApplicationsCount: number;
  winnerDropdownRef: RefObject<HTMLDivElement | null>;
};

export type RoomWorkspaceBannerAction = NonNullable<NonNullable<RoomUiScenarioState["primaryBanner"]>["action"]> | NonNullable<NonNullable<RoomUiScenarioState["primaryBanner"]>["secondaryAction"]>;
